/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { default as CancelOfferScriptJson } from "../CancelOffer.ral.json";

export const CancelOffer = new ExecutableScript<{
  market: HexString;
  offerId: HexString;
}>(Script.fromJson(CancelOfferScriptJson, "", []));
